env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_IMAGE=repo_udagram
  matrix:  
    - SERVICE=frontend
      DOCKERFILE=udagram-frontend/Dockerfile
      DOCKER_TAG=tag_frontend_latest
    - SERVICE=backend
      DOCKERFILE=udagram-api/Dockerfile
      DOCKER_TAG=tag_backend_latest

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ${DOCKERFILE} .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}


