version: '3.5'
networks:
    nw_udagram:
        driver: bridge

services:
    frontend:
        build:
            context: ./udagram-frontend
            dockerfile: Dockerfile      
        image: msd4docker/repo_udagram:tag_frontend
        container_name: akuudagram-frontend
        networks:
            - nw_udagram
        ports:
            - 8100:80
 
    reverseproxy:
        depends_on:
            - feed
            - users
        build:
            context: ./udagram-rproxy
            dockerfile: Dockerfile      
        image: msd4docker/repo_udagram:tag_rproxy
        container_name: akuudagram-rproxy
        networks:
            - nw_udagram
        ports:
            - 8080:80
 
    feed:
        build:
            context: ./udagram-api/feed
            dockerfile: Dockerfile
        image: msd4docker/repo_udagram:tag_backend_feed
        container_name: akuudagram-backend-feed
        networks:
            - nw_udagram
        volumes:
            - "/home/aku/.aws:/root/.aws"
        environment:
            - "AWS_REGION=us-west-1" 
            - "AWS_MEDIA_BUCKET=s3akuudacityudagram" 
            - "AWS_PROFILE=userAkuUdacityUdagram" 
            - "POSTGRES_USERNAME=codenameaku" 
            - "POSTGRES_PASSWORD=MSD4aws1" 
            - "POSTGRES_DATABASE=rdsAkuUdacityUdagram" 
            - "POSTGRES_HOST=rdsakuudacityudagram.cwkcejwii55z.us-west-1.rds.amazonaws.com" 
            - "POSTGRES_DB=rdsAkuUdacityUdagram" 
            - "URL=http://localhost:8100" 
            - "JWT_SECRET=helloworld"

    users:
        build:
            context: ./udagram-api/user
            dockerfile: Dockerfile      
        image: msd4docker/repo_udagram:tag_backend_users
        container_name: akuudagram-backend-users
        networks:
            - nw_udagram
        volumes:
            - "/home/aku/.aws:/root/.aws"
        environment:
            - "AWS_REGION=us-west-1" 
            - "AWS_MEDIA_BUCKET=s3akuudacityudagram" 
            - "AWS_PROFILE=userAkuUdacityUdagram" 
            - "POSTGRES_USERNAME=codenameaku" 
            - "POSTGRES_PASSWORD=MSD4aws1" 
            - "POSTGRES_DATABASE=rdsAkuUdacityUdagram" 
            - "POSTGRES_HOST=rdsakuudacityudagram.cwkcejwii55z.us-west-1.rds.amazonaws.com" 
            - "POSTGRES_DB=rdsAkuUdacityUdagram" 
            - "URL=http://localhost:8100" 
            - "JWT_SECRET=helloworld"
