apiVersion: apps/v1
kind: Deployment
metadata:
  name: akuudagram-backend-feed
  labels:
    app: akuudagram-backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akuudagram-backend-feed
  template:
    metadata:
      labels:
        app: akuudagram-backend-feed
    spec:
      containers:
      - name: akuudagram-backend-feed
        image: msd4docker/repo_udagram:tag_backend_feed
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: "us-west-1"
        - name: AWS_MEDIA_BUCKET
          value: "s3akuudacityudagram"
        - name: AWS_PROFILE
          value: "root"
        - name: POSTGRES_USERNAME
          value: "codenameaku"
        - name: POSTGRES_PASSWORD
          value: "MSD4aws1"
        - name: POSTGRES_DATABASE
          value: "rdsAkuUdacityUdagram"
        - name: POSTGRES_HOST
          value: "rdsakuudacityudagram.cwkcejwii55z.us-west-1.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "rdsAkuUdacityUdagram"
        - name: URL
          value: "http://localhost:8100"
        - name: JWT_SECRET
          value: "helloworld"
        ports:
        - containerPort: 80
      restartPolicy: Always
