apiVersion: v1
kind: Service
metadata:
  name: akuudagram-frontend
  labels:
    app: akuudagram-frontend
spec:
  selector:
    app: akuudagram-frontend
  ports:
  - name: "frontend"
    port: 8100
    targetPort: 80
  - name: "reverse-proxy"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
