apiVersion: v1
kind: Service
metadata:
  name: akuudagram-backend-users
  labels:
    app: akuudagram-backend-users
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 80
  selector:
    app: akuudagram-backend-users
